#spring.application.name=jpa
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.password=1234
#spring.datasource.username=root
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_test2?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


